---
title: Airstream Studio
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
    page-title: ''
    meta-desc: ''
exclude:
- notes
- node_modules
permalink: date
contact:
  email: info@airstreamstudio.co.uk
  tel: '07738590748'
gems:
- jekyll-sitemap
header-nav:
  left:
  - title: Home
    url: "/"
  - title: Photo booth
    url: javascript:void(0)
    children:
    - title: Interior
      url: "/airstream-photo-booth/interior.html"
    - title: Photo booth
      url: "/airstream-photo-booth/photo-booth.html"
    - title: Exterior
      url: "/airstream-photo-booth/exterior.html"
    - title: Guest books
      url: "/airstream-photo-booth/guest-books.html"
    - title: Props & features
      url: "/airstream-photo-booth/props-&-features.html"
    - title: Events
      url: "/airstream-photo-booth/events.html"
  - title: Pricing
    url: "/pricing.html"
  right:
  - title: Videos
    url: "/videos.html"
  - title: Social media
    url: "/social-media.html"
  - title: Contact
    url: "/contact.html"
footer-nav:
  col-1:
  - title: Home
    url: "/"
  - title: Photo booth
    url: javascript:void(0)
    children:
    - title: Interior
      url: "/airstream-photo-booth/interior.html"
    - title: Photo booth
      url: "/airstream-photo-booth/photo-booth.html"
    - title: Exterior
      url: "/airstream-photo-booth/exterior.html"
    - title: Guest books
      url: "/airstream-photo-booth/guest-books.html"
    - title: Props & features
      url: "/airstream-photo-booth/props-&-features.html"
    - title: Events
      url: "/airstream-photo-booth/events.html"
  - title: Pricing
    url: "/pricing.html"
  - title: Videos
    url: "/videos.html"
  col-2:
  - title: Social media
    url: "/social-media.html"
  - title: Vintage wedding suppliers
    url: "/vintage-wedding-suppliers.html"
  - title: Vintage shops sussex
    url: "/vintage-shops-sussex.html"
  - title: Vintage events
    url: "/vintage-events.html"
  - title: Contact
    url: "/contact.html"
